### ISSUE TITLE
Failed when the distance over 2m

### ISSUE THREAD

**Issue by leavessnow26** [derzu/BodySkeletonTracker#5]
Hi Derzu,

Thank you for sharing your code, and it's a good project.
I used an Orbbec Astra Pro camera, set DEPTH, compiled with windows, but facing two problems.
First, the skeleton tracking is not right, every joint is wrong. Second, it failed when the distance over 2m, is this normal?

Thanks a lot

**Comment by derzu** [comment]
Hi Leavessnow26,

The detector can work with distances over 2m, the problem is that it looks for the closest region. Maybe, when you are at a distance over 2m, there are other objects or walls that are closer, and it tries to find the skeleton in the wrong region.

Please test again in a place where the body is really the closest region of the image, even when the distance is over 2m.

If that doesn't work send me a picture of the detection to I try to understand better.

Best regards,

Derzu.

**Comment by leavessnow26** [comment]
Hi Derzu,

Thank you for your reply.
And you are right, the body is not the closest region of the image, if satisfies the conditions you said, it works very well.

Best regards,

Leavessnow26.

**Comment by derzu** [comment]
Ok, I'm glad you've made it work.

Best regards,

Derzu.
